import { createContext, useContext, useState } from 'react';

const LANGUAGES = {
  en: { code: 'en', label: 'English', short: 'EN' },
  si: { code: 'si', label: 'Sinhala', short: 'SI' },
  ta: { code: 'ta', label: 'Tamil', short: 'TA' },
};

const TRANSLATIONS = {
  en: {
    home: 'Home',
    simulate: 'Simulate',
    history: 'History',
    heroTitle: 'Turn Physics Practicals into',
    heroHighlight: 'Live Simulations',
    heroDesc: 'Upload any physics practical PDF or image and watch AI generate an interactive, real-time simulation with accurate physics and adjustable parameters.',
    startSimulating: 'Start Simulating',
    viewHistory: 'View History',
    howItWorks: 'How It Works',
    uploadTitle: 'Upload',
    uploadDesc: 'Drop a PDF or photo of any physics practical from the A/L syllabus.',
    aiTitle: 'AI Analyzes',
    aiDesc: 'Gemini AI extracts equations, parameters, and setup from your practical.',
    simTitle: 'Simulate',
    simDesc: 'Get a live, interactive simulation with sliders and real-time graphs.',
    supportedDomains: 'Supported Physics Domains',
    generateTitle: 'Generate Simulation',
    generateSubtitle: 'Upload physics practical PDFs or images to create an interactive simulation',
    dropzone: 'Drop your Physics practical files here',
    dropzoneHint: 'PDF and images (PNG, JPG, WebP) -- select multiple files, max 20MB each',
    filesSelected: 'file(s) selected',
    clearAll: 'Clear all',
    generateBtn: 'Generate Simulation',
    genFailed: 'Generation Failed',
    tryAgain: 'Try Again',
    newSimulation: 'New Simulation',
    extracting: 'Extracting text...',
    analyzing: 'Analyzing your practical...',
    generating: 'Generating simulation...',
    waitMessage: 'This usually takes 15-30 seconds',
    simHistory: 'Simulation History',
    noSimulations: 'No simulations yet',
    noSimulationsHint: 'Upload a PDF to create your first simulation',
    backToHistory: 'Back to History',
    parameters: 'Parameters',
    observables: 'Observables',
    govEquations: 'Governing Equations',
    mechanics: 'Mechanics',
    optics: 'Optics',
    thermodynamics: 'Thermodynamics',
    electricity: 'Electricity',
    waves: 'Waves',
    fluidDynamics: 'Fluid Dynamics',
    poweredBy: 'Powered by Google Gemini AI',
    tryPracticals: 'Try These Practicals',
    tryPracticalsDesc: 'Click any experiment below to generate a simulation instantly.',
    orUploadOwn: 'Or Upload Your Own',
    orUploadOwnDesc: 'Have a different practical? Upload a PDF or photo to generate a custom simulation.',
    launchSim: 'Launch Simulation',
  },
  si: {
    home: 'මුල් පිටුව',
    simulate: 'අනුකරණය',
    history: 'ඉතිහාසය',
    heroTitle: 'භෞතික විද්\u200Dයා ප්\u200Dරායෝගික පරිවර්තනය කරන්න',
    heroHighlight: 'සජීවී අනුකරණ',
    heroDesc: 'ඕනෑම භෞතික විද්\u200Dයා ප්\u200Dරායෝගික PDF හෝ පින්තූරයක් උඩුගත කරන්න, AI අන්තර්ක්\u200Dරියාකාරී අනුකරණයක් ජනනය කරයි.',
    startSimulating: 'අනුකරණය ආරම්භ කරන්න',
    viewHistory: 'ඉතිහාසය බලන්න',
    howItWorks: 'ක්\u200Dරියා කරන ආකාරය',
    uploadTitle: 'උඩුගත කරන්න',
    uploadDesc: 'උ/පෙ විෂය නිර්දේශයේ ඕනෑම භෞතික විද්\u200Dයා ප්\u200Dරායෝගිකයක PDF හෝ ඡායාරූපයක් දමන්න.',
    aiTitle: 'AI විශ්ලේෂණය',
    aiDesc: 'Gemini AI සමීකරණ, පරාමිතීන් සහ සැකසුම ඔබේ ප්\u200Dරායෝගිකයෙන් උපුටා ගනී.',
    simTitle: 'අනුකරණය',
    simDesc: 'ස්ලයිඩර් සහ තත්\u200Dකාලීන ප්\u200Dරස්ථාර සහිත සජීවී අන්තර්ක්\u200Dරියාකාරී අනුකරණයක් ලබා ගන්න.',
    supportedDomains: 'සහාය දක්වන භෞතික විද්\u200Dයා ක්ෂේත්\u200Dර',
    generateTitle: 'අනුකරණය ජනනය කරන්න',
    generateSubtitle: 'අන්තර්ක්\u200Dරියාකාරී අනුකරණයක් සෑදීමට PDF හෝ පින්තූර උඩුගත කරන්න',
    dropzone: 'ඔබේ භෞතික විද්\u200Dයා ප්\u200Dරායෝගික ගොනු මෙහි දමන්න',
    dropzoneHint: 'PDF සහ පින්තූර (PNG, JPG, WebP) -- ගොනු කිහිපයක් තෝරන්න, උපරිම 20MB',
    filesSelected: 'ගොනු තෝරා ඇත',
    clearAll: 'සියල්ල මකන්න',
    generateBtn: 'අනුකරණය ජනනය කරන්න',
    genFailed: 'ජනනය අසාර්ථක විය',
    tryAgain: 'නැවත උත්සාහ කරන්න',
    newSimulation: 'නව අනුකරණය',
    extracting: 'පෙළ උපුටා ගනිමින්...',
    analyzing: 'ඔබේ ප්\u200Dරායෝගිකය විශ්ලේෂණය කරමින්...',
    generating: 'අනුකරණය ජනනය කරමින්...',
    waitMessage: 'මෙයට සාමාන්\u200Dයයෙන් තත්පර 15-30 ක් ගත වේ',
    simHistory: 'අනුකරණ ඉතිහාසය',
    noSimulations: 'තවම අනුකරණ නැත',
    noSimulationsHint: 'ඔබේ පළමු අනුකරණය සෑදීමට PDF එකක් උඩුගත කරන්න',
    backToHistory: 'ඉතිහාසය වෙත ආපසු',
    parameters: 'පරාමිතීන්',
    observables: 'නිරීක්ෂණ',
    govEquations: 'පාලක සමීකරණ',
    mechanics: 'යාන්ත්\u200Dර විද්\u200Dයාව',
    optics: 'ප්\u200Dරකාශ විද්\u200Dයාව',
    thermodynamics: 'තාප විද්\u200Dයාව',
    electricity: 'විද්\u200Dයුත් විද්\u200Dයාව',
    waves: 'තරංග',
    fluidDynamics: 'ද්\u200Dරව ගතිකය',
    poweredBy: 'Google Gemini AI මඟින් බලගැන්වේ',
    tryPracticals: 'මෙම ප්\u200Dරායෝගික උත්සාහ කරන්න',
    tryPracticalsDesc: 'ක්ෂණිකව අනුකරණයක් ජනනය කිරීමට පහත ඕනෑම ප්\u200Dරයෝගයක් ක්ලික් කරන්න.',
    orUploadOwn: 'හෝ ඔබේම එකක් උඩුගත කරන්න',
    orUploadOwnDesc: 'වෙනත් ප්\u200Dරායෝගිකයක් තිබේද? අභිරුචි අනුකරණයක් ජනනය කිරීමට PDF හෝ ඡායාරූපයක් උඩුගත කරන්න.',
    launchSim: 'අනුකරණය දියත් කරන්න',
  },
  ta: {
    home: 'முகப்பு',
    simulate: 'உருவகப்படுத்து',
    history: 'வரலாறு',
    heroTitle: 'இயற்பியல் செய்முறைகளை மாற்றுங்கள்',
    heroHighlight: 'நேரடி உருவகப்படுத்தல்கள்',
    heroDesc: 'எந்தவொரு இயற்பியல் செய்முறை PDF அல்லது படத்தையும் பதிவேற்றுங்கள், AI ஊடாடும் உருவகப்படுத்தலை உருவாக்கும்.',
    startSimulating: 'உருவகப்படுத்தலைத் தொடங்கு',
    viewHistory: 'வரலாற்றைக் காண்க',
    howItWorks: 'இது எப்படி வேலை செய்கிறது',
    uploadTitle: 'பதிவேற்று',
    uploadDesc: 'உ/த பாடத்திட்டத்தில் உள்ள எந்த இயற்பியல் செய்முறையின் PDF அல்லது புகைப்படத்தை இடுங்கள்.',
    aiTitle: 'AI பகுப்பாய்வு',
    aiDesc: 'Gemini AI உங்கள் செய்முறையிலிருந்து சமன்பாடுகள், அளவுருக்கள் மற்றும் அமைப்பை பிரித்தெடுக்கிறது.',
    simTitle: 'உருவகப்படுத்து',
    simDesc: 'ஸ்லைடர்கள் மற்றும் நிகழ்நேர வரைபடங்களுடன் ஊடாடும் உருவகப்படுத்தலைப் பெறுங்கள்.',
    supportedDomains: 'ஆதரிக்கப்படும் இயற்பியல் துறைகள்',
    generateTitle: 'உருவகப்படுத்தலை உருவாக்கு',
    generateSubtitle: 'ஊடாடும் உருவகப்படுத்தலை உருவாக்க PDF அல்லது படங்களைப் பதிவேற்றவும்',
    dropzone: 'உங்கள் இயற்பியல் செய்முறை கோப்புகளை இங்கே விடுங்கள்',
    dropzoneHint: 'PDF மற்றும் படங்கள் (PNG, JPG, WebP) -- பல கோப்புகளைத் தேர்ந்தெடுக்கவும், அதிகபட்சம் 20MB',
    filesSelected: 'கோப்புகள் தேர்ந்தெடுக்கப்பட்டன',
    clearAll: 'அனைத்தையும் அழி',
    generateBtn: 'உருவகப்படுத்தலை உருவாக்கு',
    genFailed: 'உருவாக்கம் தோல்வியடைந்தது',
    tryAgain: 'மீண்டும் முயற்சிக்கவும்',
    newSimulation: 'புதிய உருவகப்படுத்தல்',
    extracting: 'உரையைப் பிரித்தெடுக்கிறது...',
    analyzing: 'உங்கள் செய்முறையை பகுப்பாய்வு செய்கிறது...',
    generating: 'உருவகப்படுத்தலை உருவாக்குகிறது...',
    waitMessage: 'இது பொதுவாக 15-30 வினாடிகள் எடுக்கும்',
    simHistory: 'உருவகப்படுத்தல் வரலாறு',
    noSimulations: 'இன்னும் உருவகப்படுத்தல்கள் இல்லை',
    noSimulationsHint: 'உங்கள் முதல் உருவகப்படுத்தலை உருவாக்க PDF ஐ பதிவேற்றவும்',
    backToHistory: 'வரலாற்றுக்குத் திரும்பு',
    parameters: 'அளவுருக்கள்',
    observables: 'கவனிக்கக்கூடியவை',
    govEquations: 'ஆளும் சமன்பாடுகள்',
    mechanics: 'இயக்கவியல்',
    optics: 'ஒளியியல்',
    thermodynamics: 'வெப்ப இயக்கவியல்',
    electricity: 'மின்சாரம்',
    waves: 'அலைகள்',
    fluidDynamics: 'திரவ இயக்கவியல்',
    poweredBy: 'Google Gemini AI மூலம் இயக்கப்படுகிறது',
    tryPracticals: 'இந்த செய்முறைகளை முயற்சிக்கவும்',
    tryPracticalsDesc: 'உடனடியாக உருவகப்படுத்தலை உருவாக்க கீழே உள்ள எந்த சோதனையையும் கிளிக் செய்யவும்.',
    orUploadOwn: 'அல்லது உங்கள் சொந்தத்தை பதிவேற்றவும்',
    orUploadOwnDesc: 'வேறு செய்முறை உள்ளதா? தனிப்பயன் உருவகப்படுத்தலை உருவாக்க PDF அல்லது படத்தைப் பதிவேற்றவும்.',
    launchSim: 'உருவகப்படுத்தலைத் தொடங்கு',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');

  const t = (key) => TRANSLATIONS[lang]?.[key] || TRANSLATIONS.en[key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
